default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: admin
  database: newdb
  password: 'qwerty'
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: testdb

test:
  <<: *default
  database: testdb

production:
  <<: *default
  database: testdb
