default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: illia
  password: qwerty1234
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: testdb

test:
  <<: *default
  database: testdb
